### ISSUE TITLE
Credential & token was stored, cannot delete or use other credential

### ISSUE THREAD

**Issue by shadowforward** [KoenZomers/RingRecordingDownload#10]
I understand the token was stored for unattended run. it will utilize the refresh token from the first run to authenticate for all subsequent runs. But this is annoying particularly if want to switch user, or account password has been updated. Looks like there is no way to reset the stored token?

**Comment by KoenZomers** [comment]
Hi @shadowforward. Good point. I've added ```-ignorecachedtoken``` to the tool which you can use to prevent the cached token from being used. I'm preparing the new release which includes this option now.

**Comment by KoenZomers** [comment]
[Version 2.0.3.0](https://github.com/KoenZomers/RingRecordingDownload/releases/tag/2.0.3.0) has been released in which the ```-ignorecachedtoken``` option has been added
