### ISSUE TITLE
Ring Device ID

### ISSUE THREAD

**Issue by ADHaddock** [KoenZomers/RingRecordingDownload#11]
Hello,

I am struggling to get the download to specify a particular device. Is the Device ID for a Ring device the Mac address or something else?

Thanks,

Adam

**Comment by djdem29** [comment]
Has this been solved?

**Comment by markbchavez** [comment]
I used the other Ring tool by Koen called RingSnapshotDownload to identify the deviceID as it has a -list option to output all the Ring devices. These worked in the RingRecordingDownload tool as input for -deviceid .

**Comment by KoenZomers** [comment]
Sorry for the late response here. @markbchavez his response brought this back to my attention. I've updated this tool to also include a `-list` option to show all the available Ring devices and reveal the deviceid.

**Comment by KoenZomers** [comment]
Please see the latest release
