### ISSUE TITLE
On Mac OS x64 "RingRecordingDownload: The term 'RingRecordingDownload' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

### ISSUE THREAD

**Issue by thecbucks** [KoenZomers/RingRecordingDownload#19]
Not sure what I am doing wrong but downloaded latest version of PowerShell installed and downloaded RingRecordingDownload Mac OS automatically unzips and puts a file in downloads for RingRecordingDownload (no extension). I try to run command in PowerShell and get this message. 

PS /Users/na/Downloads> RingRecordingDownload
RingRecordingDownload: The term 'RingRecordingDownload' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command "RingRecordingDownload" was not found, but does exist in the current location.
PowerShell does not load commands from the current location by default (see ''Get-Help about_Command_Precedence'').

If you trust this command, run the following command instead:
PS /Users/na/Downloads>

**Comment by danespinosa** [comment]
I am not a pwsh MacOS expert, nor have a MacOS to test this but from a command line can you run powershell like this: 
```powershell
pwsh RingRecordingDownload
``` 
Also, if pwsh is already running I believe you can try executing the program like below by adding **.\\** before the executable like below
```powershell
PS /Users/na/Downloads> .\RingRecordingDownload
``` 

I am going to close this issue since it's stale (~3 months) but feel free to re-open
