### ISSUE TITLE
Can't find the RingRecordingDownload 1.1.0

### ISSUE THREAD

**Issue by phantom7970** [KoenZomers/RingRecordingDownload#3]
Hello,
What is the latest version of the RingRecordingDownload ?

The changelog references V 1.1.0 but the latest I am able to find is version:1.0.2

**Comment by KoenZomers** [comment]
Well noticed, sorry for the confusion. I'll straighten it up.

**Comment by KoenZomers** [comment]
Added [the correct 1.1.0.0 release now](https://github.com/KoenZomers/RingRecordingDownload/releases/tag/1.1.0.0) but noticed Ring has changed their API. Will look into it tonight to fix that.

**Comment by KoenZomers** [comment]
I was still testing using old code. Works fine now for me. Closing this issue. Feel free to reopen if it still doesn't work with you using this latest version.
