### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by divemasterjm** [KoenZomers/RingRecordingDownload#6]
can you add 2FA? is not working due to ring restrictions

**Comment by ronwarner** [comment]
I noticed you closed your own issue.  I'm having the same problem.  Did you find a workaround?

**Comment by KoenZomers** [comment]
Two factor authentication should be supported. Reopening this to test it myself if something may have been broken with the port to .NET core.

**Comment by KoenZomers** [comment]
I can reproduce it. Looking into the cause.

**Comment by KoenZomers** [comment]
Fixed it. Releasing a new version.

**Comment by KoenZomers** [comment]
[Version 2.0.1.0](https://github.com/KoenZomers/RingRecordingDownload/releases/tag/2.0.1.0)

I assume this will fix it for you. Therefore closing this issue. If the problem still occurs for you, feel free to post back.
