### ISSUE TITLE
Ring now enforces a version of 2FA; authentication fails

### ISSUE THREAD

**Issue by ronwarner** [KoenZomers/RingRecordingDownload#7]
Recently, Ring began rolling out a change where, upon login, a user is emailed a six-digit code they must provide back to the page in order to be logged in.  This is entirely separate from their optional two-factor authentication, and it does not appear to have an opt-out option.  Since this update, I've been unable to use this code to authenticate and download videos.  The call to `session.Authenticate().Wait()` results in the following exception:
```
System.AggregateException: 'One or more errors occurred.'
Inner Exception
WebException: The remote server returned an error: (412) Precondition Failed.
```
Meanwhile, I receive an email from Ring, providing the six-digit code, but of course I don't have any way to use it.

Is there some work around already in place for this scenario, or will this require a change to your API project?

Thanks!

**Comment by KoenZomers** [comment]
Thanks @ronwarner for reporting this in detail. To keep it central in one topic I will close this and continue in Issue #6.
